package test;

import com.banorte.BanorteException;
import com.banorte.pinpad.Vx820Segura;
import java.util.HashMap;
import javax.swing.*;

public class DeviceConfiguration extends JFrame {

    /**
     * Constructor for component initialization
     */
    public DeviceConfiguration() {
        initComponents();
        setDefaultInformation();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        lblPort = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        lblVelocity = new javax.swing.JLabel();
        txtVelocity = new javax.swing.JTextField();
        lblParity = new javax.swing.JLabel();
        txtParity = new javax.swing.JTextField();
        lblDataBit = new javax.swing.JLabel();
        txtDataBit = new javax.swing.JTextField();
        lblStopBit = new javax.swing.JLabel();
        txtStopBit = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        initPanel = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JPinpad v0.1");
        setName("frmInit"); // NOI18N

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(400, 300));
        mainPanel.setLayout(new java.awt.BorderLayout());

        titlePanel.setName("titlePanel"); // NOI18N
        titlePanel.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Iniciar Pinpad VeriFone vx820");
        lblTitle.setMaximumSize(new java.awt.Dimension(206, 33));
        lblTitle.setMinimumSize(new java.awt.Dimension(206, 33));
        lblTitle.setName("lblTitle"); // NOI18N
        lblTitle.setPreferredSize(new java.awt.Dimension(206, 33));
        titlePanel.add(lblTitle, java.awt.BorderLayout.CENTER);

        mainPanel.add(titlePanel, java.awt.BorderLayout.NORTH);

        menuPanel.setName("menuPanel"); // NOI18N
        menuPanel.setPreferredSize(new java.awt.Dimension(400, 231));
        java.awt.GridBagLayout menuPanelLayout = new java.awt.GridBagLayout();
        menuPanelLayout.columnWeights = new double[] {0.0};
        menuPanelLayout.rowWeights = new double[] {0.0};
        menuPanel.setLayout(menuPanelLayout);

        lblPort.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPort.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPort.setText("Puerto");
        lblPort.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPort.setName("lblPort"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        menuPanel.add(lblPort, gridBagConstraints);

        txtPort.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPort.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPort.setToolTipText("Número de puerto de comunicación");
        txtPort.setMinimumSize(new java.awt.Dimension(100, 30));
        txtPort.setName("txtPort"); // NOI18N
        txtPort.setPreferredSize(new java.awt.Dimension(100, 30));
        txtPort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPortKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        menuPanel.add(txtPort, gridBagConstraints);

        lblVelocity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblVelocity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVelocity.setText("Velocidad");
        lblVelocity.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblVelocity.setName("lblVelocity"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        menuPanel.add(lblVelocity, gridBagConstraints);

        txtVelocity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtVelocity.setToolTipText("Velocidad de respuesta");
        txtVelocity.setMinimumSize(new java.awt.Dimension(200, 30));
        txtVelocity.setName("txtVelocity"); // NOI18N
        txtVelocity.setPreferredSize(new java.awt.Dimension(200, 30));
        txtVelocity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVelocityKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1.0;
        menuPanel.add(txtVelocity, gridBagConstraints);
        txtVelocity.getAccessibleContext().setAccessibleName("");

        lblParity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblParity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblParity.setText("Paridad");
        lblParity.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblParity.setName("lblParity"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        menuPanel.add(lblParity, gridBagConstraints);

        txtParity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtParity.setToolTipText("Paridad de datos");
        txtParity.setMinimumSize(new java.awt.Dimension(200, 30));
        txtParity.setName("txtParity"); // NOI18N
        txtParity.setPreferredSize(new java.awt.Dimension(200, 30));
        txtParity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtParityKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weighty = 1.0;
        menuPanel.add(txtParity, gridBagConstraints);

        lblDataBit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDataBit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDataBit.setText("Bits de Datos ");
        lblDataBit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDataBit.setName("lblDataBit"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        menuPanel.add(lblDataBit, gridBagConstraints);

        txtDataBit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDataBit.setToolTipText("Bits de datos");
        txtDataBit.setMinimumSize(new java.awt.Dimension(200, 30));
        txtDataBit.setName("txtDataBit"); // NOI18N
        txtDataBit.setPreferredSize(new java.awt.Dimension(200, 30));
        txtDataBit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataBitKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weighty = 1.0;
        menuPanel.add(txtDataBit, gridBagConstraints);

        lblStopBit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblStopBit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStopBit.setText("Bits de Paro");
        lblStopBit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblStopBit.setName("lblStopBit"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        menuPanel.add(lblStopBit, gridBagConstraints);

        txtStopBit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtStopBit.setToolTipText("Bits de paro");
        txtStopBit.setMinimumSize(new java.awt.Dimension(200, 30));
        txtStopBit.setName("txtStopBit"); // NOI18N
        txtStopBit.setPreferredSize(new java.awt.Dimension(200, 30));
        txtStopBit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStopBitKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weighty = 1.0;
        menuPanel.add(txtStopBit, gridBagConstraints);

        btnStart.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pinpad_start.png"))); // NOI18N
        btnStart.setText("Iniciar");
        btnStart.setToolTipText("Iniciar la configuración del dispositivo");
        btnStart.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnStart.setMaximumSize(new java.awt.Dimension(100, 33));
        btnStart.setMinimumSize(new java.awt.Dimension(100, 33));
        btnStart.setName("btnStart"); // NOI18N
        btnStart.setPreferredSize(new java.awt.Dimension(100, 33));
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        btnStart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnStartKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        menuPanel.add(btnStart, gridBagConstraints);

        mainPanel.add(menuPanel, java.awt.BorderLayout.CENTER);

        initPanel.setName("initPanel"); // NOI18N
        initPanel.setLayout(new java.awt.BorderLayout());

        btnNext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/next.png"))); // NOI18N
        btnNext.setText("Siguiente");
        btnNext.setToolTipText("Siguiente formulario");
        btnNext.setMaximumSize(new java.awt.Dimension(83, 33));
        btnNext.setMinimumSize(new java.awt.Dimension(83, 33));
        btnNext.setName("btnNext"); // NOI18N
        btnNext.setPreferredSize(new java.awt.Dimension(83, 33));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        btnNext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnNextKeyPressed(evt);
            }
        });
        initPanel.add(btnNext, java.awt.BorderLayout.CENTER);

        mainPanel.add(initPanel, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        openFrameKey();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        start();
    }//GEN-LAST:event_btnStartActionPerformed

    private void txtPortKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPortKeyPressed
        setFocus(evt);
    }//GEN-LAST:event_txtPortKeyPressed

    private void txtVelocityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVelocityKeyPressed
        setFocus(evt);
    }//GEN-LAST:event_txtVelocityKeyPressed

    private void txtParityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParityKeyPressed
        setFocus(evt);
    }//GEN-LAST:event_txtParityKeyPressed

    private void txtDataBitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataBitKeyPressed
        setFocus(evt);
    }//GEN-LAST:event_txtDataBitKeyPressed

    private void txtStopBitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStopBitKeyPressed
        setFocus(evt);
    }//GEN-LAST:event_txtStopBitKeyPressed

    private void btnNextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnNextKeyPressed
        setFocus(evt);
    }//GEN-LAST:event_btnNextKeyPressed

    private void btnStartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnStartKeyPressed
        setFocus(evt);
    }//GEN-LAST:event_btnStartKeyPressed
    
    /**
     * Sets the JTextField information
     */
    public void setDefaultInformation(){
        txtPort.setText("COM9");
        txtVelocity.setText("19200");
        txtParity.setText("N");
        txtStopBit.setText("1");
        txtDataBit.setText("8");
    }
    
    /**
     * Sets the key where the cursor must be located
     * @param evt the key event
     */
    public void setFocus(java.awt.event.KeyEvent evt) {
        String key = getKeySource(evt);
        int keyCode = evt.getKeyCode();                
        
        if(keyCode == 40) {                        
            switch(key){
                case "txtPort": txtVelocity.requestFocusInWindow(); break;
                case "txtVelocity": txtParity.requestFocusInWindow(); break;
                case "txtParity": txtDataBit.requestFocusInWindow(); break;
                case "txtDataBit": txtStopBit.requestFocusInWindow(); break;
                case "txtStopBit": btnStart.requestFocusInWindow(); break;
                case "btnStart": btnNext.requestFocusInWindow(); break;
            }
        }
        else if(keyCode == 38){
            switch(key){                
                case "txtVelocity": txtPort.requestFocusInWindow(); break;
                case "txtParity": txtVelocity.requestFocusInWindow(); break;
                case "txtDataBit": txtParity.requestFocusInWindow(); break;
                case "txtStopBit": txtDataBit.requestFocusInWindow(); break;
                case "btnStart": txtStopBit.requestFocusInWindow(); break;
                case "btnNext": btnStart.requestFocusInWindow(); break;
            }
        }
        else if(keyCode == 10 && key.equals("btnNext")){
            openFrameKey();
        }
        else if(keyCode == 10 && key.equals("btnStart")){
            start();
        }
    }
    
    /**
     * Gets the name of the key event source.
     * @param evt the key event
     * @return the name of the source where the event is found
     */
    public String getKeySource(java.awt.event.KeyEvent evt) {
        String keySource = evt.getSource().getClass().getSimpleName();
        String key = null;
        
        if(keySource.equals("JTextField"))
            key = ((JTextField)evt.getSource()).getName();
        else if(keySource.equals("JButton"))
            key = ((JButton)evt.getSource()).getName();
        
        return key;
    }
    
    /**
     * Opens the KeyLoader window
     */
    public void openFrameKey(){
        this.setVisible(false);
        
        KeyLoader frm = new KeyLoader();
        frm.setVisible(true);        
    }
    
    /**
     * Starts the device configuration
     */
    public void start(){
        Vx820Segura pinpad = new Vx820Segura("EN");
        
        //Initial parameters
        HashMap configuration = new HashMap(5);
        
        configuration.put("PORT", txtPort.getText());
        configuration.put("BAUD_RATE", txtVelocity.getText());
        configuration.put("PARITY", txtParity.getText());
        configuration.put("STOP_BITS", txtStopBit.getText());
        configuration.put("DATA_BITS", txtDataBit.getText());
        
        //Pinpad initializated according to the established parameters
        try {
            pinpad.prepareDevice(configuration);
            
            JOptionPane.showMessageDialog(null, "Device successfully initialized");
        }
        catch(BanorteException e) {
            System.out.println("Pinpad initialization error: " + e.getMessage());
        }
    }
    
    /**
     * Main method for application execution
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeviceConfiguration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeviceConfiguration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnStart;
    private javax.swing.JPanel initPanel;
    private javax.swing.JLabel lblDataBit;
    private javax.swing.JLabel lblParity;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblStopBit;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVelocity;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField txtDataBit;
    private javax.swing.JTextField txtParity;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtStopBit;
    private javax.swing.JTextField txtVelocity;
    // End of variables declaration//GEN-END:variables
}