package test;

import com.banorte.BanorteException;
import com.banorte.pinpad.Vx820Segura;
import com.banorte.ConectorBanorte;
import java.util.HashMap;
import javax.swing.*;

public class Sales extends javax.swing.JFrame {
    
    //Llenamos la tabla para enviar la transacción
    public Sales() {
        initComponents();
        
        setDefaultInformation();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titlePanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        salePanel = new javax.swing.JPanel();
        lblMerchantId = new javax.swing.JLabel();
        txtMerchantId = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblTerminalId = new javax.swing.JLabel();
        txtTerminalId = new javax.swing.JTextField();
        lblAmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lblControlNumber = new javax.swing.JLabel();
        txtControlNumber = new javax.swing.JTextField();
        lblLanguage = new javax.swing.JLabel();
        txtLanguage = new javax.swing.JTextField();
        lblUrl = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        btnSale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JPinpad v0.1");
        setMinimumSize(new java.awt.Dimension(600, 400));
        setName("frmSales"); // NOI18N

        titlePanel.setMinimumSize(new java.awt.Dimension(600, 20));
        titlePanel.setName("titlePanel"); // NOI18N
        titlePanel.setPreferredSize(new java.awt.Dimension(600, 20));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setText("Ventas");
        lblTitle.setName("lblTitle"); // NOI18N

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titlePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTitle)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titlePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTitle)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(titlePanel, java.awt.BorderLayout.NORTH);

        salePanel.setMinimumSize(new java.awt.Dimension(600, 380));
        salePanel.setName("salePanel"); // NOI18N
        salePanel.setPreferredSize(new java.awt.Dimension(600, 380));
        salePanel.setLayout(new java.awt.GridBagLayout());

        lblMerchantId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMerchantId.setText("Merchant ID");
        lblMerchantId.setName("lblMerchantId"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        salePanel.add(lblMerchantId, gridBagConstraints);

        txtMerchantId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMerchantId.setMinimumSize(new java.awt.Dimension(200, 30));
        txtMerchantId.setName("txtMerchantId"); // NOI18N
        txtMerchantId.setPreferredSize(new java.awt.Dimension(200, 30));
        txtMerchantId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMerchantIdKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        salePanel.add(txtMerchantId, gridBagConstraints);

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUser.setText("User");
        lblUser.setName("lblUser"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        salePanel.add(lblUser, gridBagConstraints);

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUser.setMinimumSize(new java.awt.Dimension(200, 30));
        txtUser.setName("txtUser"); // NOI18N
        txtUser.setPreferredSize(new java.awt.Dimension(200, 30));
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        salePanel.add(txtUser, gridBagConstraints);

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPassword.setText("Password");
        lblPassword.setName("lblPassword"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        salePanel.add(lblPassword, gridBagConstraints);

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPassword.setMinimumSize(new java.awt.Dimension(200, 30));
        txtPassword.setName("txtPassword"); // NOI18N
        txtPassword.setPreferredSize(new java.awt.Dimension(200, 30));
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        salePanel.add(txtPassword, gridBagConstraints);

        lblTerminalId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTerminalId.setText("Terminal ID");
        lblTerminalId.setName("lblTerminalId"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        salePanel.add(lblTerminalId, gridBagConstraints);

        txtTerminalId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTerminalId.setMinimumSize(new java.awt.Dimension(200, 30));
        txtTerminalId.setName("txtTerminalId"); // NOI18N
        txtTerminalId.setPreferredSize(new java.awt.Dimension(200, 30));
        txtTerminalId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTerminalIdKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        salePanel.add(txtTerminalId, gridBagConstraints);

        lblAmount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAmount.setText("Amount");
        lblAmount.setName("lblAmount"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        salePanel.add(lblAmount, gridBagConstraints);

        txtAmount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAmount.setMinimumSize(new java.awt.Dimension(200, 30));
        txtAmount.setName("txtAmount"); // NOI18N
        txtAmount.setPreferredSize(new java.awt.Dimension(200, 30));
        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAmountKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        salePanel.add(txtAmount, gridBagConstraints);

        lblControlNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblControlNumber.setText("Control Number");
        lblControlNumber.setName("lblControlNumber"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        salePanel.add(lblControlNumber, gridBagConstraints);

        txtControlNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtControlNumber.setMinimumSize(new java.awt.Dimension(200, 30));
        txtControlNumber.setName("txtControlNumber"); // NOI18N
        txtControlNumber.setPreferredSize(new java.awt.Dimension(200, 30));
        txtControlNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtControlNumberKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        salePanel.add(txtControlNumber, gridBagConstraints);

        lblLanguage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLanguage.setText("Language");
        lblLanguage.setName("lblLanguage"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        salePanel.add(lblLanguage, gridBagConstraints);

        txtLanguage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLanguage.setMinimumSize(new java.awt.Dimension(200, 30));
        txtLanguage.setName("txtLanguage"); // NOI18N
        txtLanguage.setPreferredSize(new java.awt.Dimension(200, 30));
        txtLanguage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLanguageKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        salePanel.add(txtLanguage, gridBagConstraints);

        lblUrl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUrl.setText("URL");
        lblUrl.setName("lblUrl"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        salePanel.add(lblUrl, gridBagConstraints);

        txtUrl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUrl.setMinimumSize(new java.awt.Dimension(400, 30));
        txtUrl.setName("txtUrl"); // NOI18N
        txtUrl.setPreferredSize(new java.awt.Dimension(400, 30));
        txtUrl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUrlKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        salePanel.add(txtUrl, gridBagConstraints);

        btnSale.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sales.png"))); // NOI18N
        btnSale.setText("Vender");
        btnSale.setMaximumSize(new java.awt.Dimension(100, 33));
        btnSale.setMinimumSize(new java.awt.Dimension(100, 33));
        btnSale.setName("btnSale"); // NOI18N
        btnSale.setPreferredSize(new java.awt.Dimension(100, 33));
        btnSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleActionPerformed(evt);
            }
        });
        btnSale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSaleKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.weighty = 1.0;
        salePanel.add(btnSale, gridBagConstraints);

        getContentPane().add(salePanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleActionPerformed
        sale();
    }//GEN-LAST:event_btnSaleActionPerformed

    private void txtTerminalIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTerminalIdKeyPressed
        setFocus(evt);
    }//GEN-LAST:event_txtTerminalIdKeyPressed

    private void txtMerchantIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMerchantIdKeyPressed
        setFocus(evt);
    }//GEN-LAST:event_txtMerchantIdKeyPressed

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
        setFocus(evt);
    }//GEN-LAST:event_txtUserKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        setFocus(evt);
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void txtAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyPressed
        setFocus(evt);
    }//GEN-LAST:event_txtAmountKeyPressed

    private void txtControlNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtControlNumberKeyPressed
        setFocus(evt);
    }//GEN-LAST:event_txtControlNumberKeyPressed

    private void txtLanguageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLanguageKeyPressed
        setFocus(evt);
    }//GEN-LAST:event_txtLanguageKeyPressed

    private void txtUrlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUrlKeyPressed
        setFocus(evt);
    }//GEN-LAST:event_txtUrlKeyPressed

    private void btnSaleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSaleKeyPressed
        setFocus(evt);
    }//GEN-LAST:event_btnSaleKeyPressed

    /**
     * Sets the Sales frame's information
     */
    public void setDefaultInformation(){
        txtMerchantId.setText("");
        txtUser.setText("");
        txtPassword.setText("");
        txtTerminalId.setText("");
        txtControlNumber.setText("");
        txtAmount.setText("0.01");
        txtLanguage.setText("EN");
        txtUrl.setText("https://via.pagosbanorte.com/InterredesSeguro");
    }
    
    /**
     * Sets the key where the cursor must be located
     * @param evt the key event
     */
    public void setFocus(java.awt.event.KeyEvent evt) {
        String key = getKeySource(evt);
        int keyCode = evt.getKeyCode();
        
        if(keyCode == 40) {                        
            switch(key){
                case "txtMerchantId": txtUser.requestFocusInWindow(); break;
                case "txtUser": txtPassword.requestFocusInWindow(); break;
                case "txtPassword": txtTerminalId.requestFocusInWindow(); break;
                case "txtTerminalId": txtAmount.requestFocusInWindow(); break;
                case "txtAmount": txtControlNumber.requestFocusInWindow(); break;
                case "txtControlNumber": txtLanguage.requestFocusInWindow(); break;
                case "txtLanguage": txtUrl.requestFocusInWindow(); break;
                case "txtUrl": btnSale.requestFocusInWindow(); break;
            }
        }
        else if(keyCode == 38){
            switch(key){                
                case "txtUser": txtMerchantId.requestFocusInWindow(); break;
                case "txtPassword": txtUser.requestFocusInWindow(); break;
                case "txtTerminalId": txtPassword.requestFocusInWindow(); break;                
                case "txtAmount": txtTerminalId.requestFocusInWindow(); break;                
                case "txtControlNumber": txtAmount.requestFocusInWindow(); break;
                case "txtLanguage": txtControlNumber.requestFocusInWindow(); break;
                case "txtUrl": txtLanguage.requestFocusInWindow(); break;
                case "btnSale": txtUrl.requestFocusInWindow(); break;
            }
        }
        else if(keyCode == 10 && key.equals("btnSale")){
            sale();
        }                
    }
    
    /**
     * Gets the name of the key event source.
     * @param evt the key event
     * @return the name of the source where the event is found
     */
    public String getKeySource(java.awt.event.KeyEvent evt) {
        String keySource = evt.getSource().getClass().getSimpleName();
        String key = null;
        
        if(keySource.equals("JTextField"))
            key = ((JTextField)evt.getSource()).getName();
        else if(keySource.equals("JButton"))
            key = ((JButton)evt.getSource()).getName();
        
        return key;
    }
    
    public void sale(){
        //Pinpad object creation
        Vx820Segura pinpad  = new Vx820Segura("EN");

        //Creation of  HashMaps for setting card reading parameters
        HashMap inputReader = new HashMap(20);
        HashMap outputReader = new HashMap(20);
        
        //Creation of HashMaps for setting transaction parameters
        HashMap inputParameters = new HashMap(20);
        HashMap outputParameters = new HashMap(20);

        //Input parameters for card reading
        String amount = "0.01";
        String mobilePayment = "0";
        inputReader.put("AMOUNT", amount);
        inputReader.put("PAGO_MOVIL", mobilePayment);

        //Card reading request
        try {
            pinpad.readCard(inputReader, outputReader);
        }
        catch(BanorteException e) {
            System.out.println("Card reading failed " + e.getMessage());
        }

        //Card reading retrieval
        //String Track1 = (String) leerSalida.get("TRACK1");
        String track2= (String) outputReader.get("TRACK2");

        //Input type determination (Banda, Chip, Fallback)
        String posEntryMode = (String) outputReader.get("ENTRY_MODE");
        String declinedChip = "";
        String emvTags = "";

        //Obtaining EMVTAGS in case of CHIP mode
        if (posEntryMode.equals("CHIP")) {
            emvTags = (String) outputReader.get("EMV_TAGS");
            inputParameters.put("EMV_TAGS", emvTags);
            declinedChip = (String)outputReader.get("CHIP_DECLINED");
        }

        //Validate if is not Offline declined by DECLINADA_CHIP variable value
        if (declinedChip.equals("1")) {
            //End transaction
            System.out.println("Transaction declined offline");
            JOptionPane.showMessageDialog(null,"Declined Offline");
        }
        else {
            //Sending transaction to Banorte by using readCard method
            //Setting HashMaps transaction parameters
            inputParameters.put("MERCHANT_ID",txtMerchantId.getText());
            inputParameters.put("USER", txtUser.getText());
            inputParameters.put("PASSWORD", txtPassword.getText());
            inputParameters.put("CMD_TRANS", "AUTH");
            inputParameters.put("TERMINAL_ID", txtTerminalId.getText());
            inputParameters.put("CONTROL_NUMBER", txtControlNumber.getText());
            inputParameters.put("MODE", "PRD");
            inputParameters.put("AMOUNT", amount);
            inputParameters.put("TRACK2", track2);
            inputParameters.put("ENTRY_MODE", posEntryMode);
            inputParameters.put("RESPONSE_LANGUAGE", "EN");
            inputParameters.put("BANORTE_URL", "https://via.pagosbanorte.com/InterredesSeguro");

            //Validamos si el Track1 está presente
            //if (!"".equals(Track1))
            //{
            //parametrosEntrada.put("TRACK1", EmvTags);
            //}

            //Processing the transaction
            try {
                pinpad.processTransaction(inputParameters, outputParameters);
            } 
            catch (BanorteException e) {
                System.out.println("Transaction processing failed: " + e.getMessage());
            }

            //CHIP card mode validation
            if (posEntryMode.equals("CHIP")) {
                //Creation of HashMaps for notifying parameters result
                HashMap notifyInputParameters = new HashMap(20);
                HashMap notifyOutputParameters = new HashMap(20);
                
                //Obtaingin transaction process output data
                String payworksResult = (String) outputParameters.get("PAYW_RESULT");
                String authenticationCode = (String)outputParameters.get("AUTH_CODE");
                String emvData = (String)outputParameters.get("EMV_TAGS");
                
                //Null precense
                //Validating transaction response
                if(payworksResult != null) {
                    
                    //Validating DATOS_EMV data
                    if (emvData != null) {
                        notifyInputParameters.put("EMV_TAGS", emvData);
                    }
                    
                    if (payworksResult.equals("A")) {
                        notifyInputParameters.put("RESULT", "APPROVED");
                        notifyInputParameters.put("AUTH_CODE", authenticationCode);
                    }
                    else if (payworksResult.equals("D")) {
                        notifyInputParameters.put("RESULT", "DECLINED");
                    }
                    else {
                        notifyInputParameters.put("RESULT", "NO_RESPONSE");
                    }
                }
                else {
                    notifyInputParameters.put("RESULT", "NO_RESPONSE");
                }

                //Notify transaction result
                try {
                    pinpad.notifyResult(notifyInputParameters, notifyOutputParameters);
                }
                catch (BanorteException e) {
                    System.out.println("Result notification error: " +e.getMessage());
                }

                //Obtaining transaction result notification
                String emvResult = (String) notifyOutputParameters.get("EMV_RESULT");

                //Validation of resultadoEMV
                if (emvResult != null) {
                    if (emvResult.equals("D") && payworksResult.equals("A")) {
                        JOptionPane.showMessageDialog(null,"DECLINADA EMV");
                        
                        //Reverse generation for EMV declination
                        //HashMaps creation
                        HashMap inputReverse = new HashMap(20);
                        HashMap outputReverse = new HashMap(20);
                        
                        //Obtaining transaction reference
                        String reference = (String) outputParameters.get("REFERENCE");
                        
                        //Setting HashMap parameters
                        inputReverse.put("MERCHANT_ID", "7395007");
                        inputReverse.put("USER", "a7395007");
                        inputReverse.put("PASSWORD", "*******");
                        inputReverse.put("CMD_TRANS", "REVERSAL");
                        inputReverse.put("TERMINAL_ID", "327783832");
                        inputReverse.put("REFERENCE", reference);
                        inputReverse.put("MODE", "PRD");
                        inputReverse.put("RESPONSE_LANGUAGE", "EN");
                        inputReverse.put("BANORTE_URL", "https://via.pagosbanorte.com/InterredesSeguro");
                        
                        //Como fue un declinado EMV se envía el parámetro CAUSE con valor fijo 17
                        inputReverse.put("CAUSE", "17");

                        //Método Enviar Transacción para enviar el reverso
                        try {
                            ConectorBanorte.sendTransaction(inputReverse,outputReverse);
                        }
                        catch(BanorteException e) {
                            System.out.println("Operation sending failed: " +
                            e.getMessage());
                        }
                    }
                    else if (emvResult.equals("A") && payworksResult.equals("A")) {
                        JOptionPane.showMessageDialog(null,"APROBADA");
                    }
                    else {
                        JOptionPane.showMessageDialog(null,"DECLINADA1");
                    }
                }
                else {
                    //Si la transacción fue realizada con banda magnética
                    String result = (String)outputParameters.get("PAYW_RESULT");

                    //Únicamente se valida el resultado de Payworks
                    if (result.equals("A")) {
                        String authCode = (String) outputParameters.get("AUTH_CODE");
                        JOptionPane.showMessageDialog(null,"APROBADA: " + authCode);
                    }
                    else {
                        JOptionPane.showMessageDialog(null,"DECLINADA2");
                    }
                }
            }
        }

        //Terminar transacción
        try {
            pinpad.endTransaction();
        } 
        catch(BanorteException e) {
            System.out.println("Transaction ending failed: " +
            e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSale;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblControlNumber;
    private javax.swing.JLabel lblLanguage;
    private javax.swing.JLabel lblMerchantId;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTerminalId;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUrl;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel salePanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtControlNumber;
    private javax.swing.JTextField txtLanguage;
    private javax.swing.JTextField txtMerchantId;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtTerminalId;
    private javax.swing.JTextField txtUrl;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}